### PR TITLE
updated the tabs component - js, sass, and html to accommodate a more…

### PR DESCRIPTION
**Pull request by mbfitz**
updated the tabs component - js, sass, and html to accommodate a more flexible and mobile-friendly solution. HTML is super flexible now and sass has been updated to allow for top-aligned and left-aligned tabs. Mobile automatically stacks tabs and panels in order. Here's the preview link:

https://htmlpreview.github.io/?https://github.com/imarc/boilerplate/blob/dd68fc725de99c54fd955a7943abee1f0f1fa657/demo/tabs.html

### CODE REVIEW

**Comment by marcelmoreau** [comment]
Thank you for doing this

- Emmet could be simplified to .tabs>(.tab.active+.panel.active)+(.tab+.panel)*2 – we were missing the active classes
- can we carry over the example HTML as seen in the other components? This will output this on sassdoc.
- we should probably say in the description that the $width is only available for the first example
- maybe reduce the space between tab label and panel content on mobile

**Comment by marcelmoreau** [comment]
@mbfitz can you come back to this next week?

**Comment by mbfitz** [comment]
@marcelmoreau - yes! planning on finishing up this week.

**Comment by mbfitz** [comment]
@marcelmoreau - this is all set! new preview available here: https://htmlpreview.github.io/?https://github.com/imarc/boilerplate/blob/ba57fcd3dbb013b127870d61df10443a67d1cb62/demo/tabs.html

**Comment by khamer** [comment]
* Let's not use `<p>` tags for the tab labels
* I'd update the JS to not remove the active class from the active tab, so if they click the same tab again, it doesn't remove the class and add it back real quick - which can cause weird CSS transition issues

**Comment by mbfitz** [comment]
Updated based on @khamer's feedback. New preview link: https://htmlpreview.github.io/?https://github.com/imarc/boilerplate/blob/ede23ef749063d50b9b7bdbaabc7a327407fd6ac/demo/tabs.html

**Comment by marcelmoreau** [comment]
- if we are going to use `span` for the tabs, we will need to update both emmet shorthands to `span.tab` so they don't default to `div`
  - vertical tabs emmet prints out 4 sets...should be 3
  - let’s use a `div.tabs` instead of `section.tabs` to match outer-most container like other components
  - just double-check both emmets after all this work
- can we add some sort of visual styling to the vertical tabs? background-color? border? just something that makes them apparent
- you might consider removing `cursor: pointer;` from a tab that is already active

**Comment by marcelmoreau** [comment]
please make sure this is also documented accurately within `_components.scss` for sassdoc purposes

**Comment by marcelmoreau** [comment]
After using this on a project, we should not assigning a hard `flex-basis` to the tabs. Adding an additional tab/panel set breaks the layout. Setting `.tabs` to `flex-basis: 0` and `white-space: nowrap` will allow for these to grow gracefully.

I have not used the vertical tab component yet, but the `width` set on the panel along with the `column wrap` flex container makes me uneasy. I tried to remove this set `width` in order to play with `flex-grow` and `flex-shrink`, but those don't behave the same at all in a column flex orientation. Not sure of the action item here, but I am wondering how closely we will be able to match our designs with this setup.

**Pull request closed without merging**
