### PR TITLE
Nav variants

### PR DESCRIPTION
**Pull request by marcelmoreau**
- removed a bit of styles
- hiding 'previous' and 'next' copy via screen reader preferred hiding method
- html `i` element works nicely for the next/prev
- pagination mixin can take a param of `center`, `flex-start`, `flex-end`

### CODE REVIEW

**Comment by mbfitz** [comment]
Should we add hover styles to the Plain Nav and Breadcrumbs? I think it makes sense for progress not to have them, but the others seem like it would be nice to have.

**Comment by marcelmoreau** [comment]
My work was specifically only on the pagination as I hope to bring it into my search listing

**Comment by khamer** [comment]
I've cleaned up this pull request, really focusing on just two components:

* breadcrumbs
* progress

**Comment by marcelmoreau** [comment]
For progress, the solid white color breaks down with the skewed pseudo-elements at smaller screens
screen shot 2017-01-17 at 9 44 49 am

**Comment by marcelmoreau** [comment]
resolved the issue above

**Pull request merged**
