### PR TITLE
updates the way we handle media queries 

### PR DESCRIPTION
**Pull request by mbfitz**
removes mq section from app.scss and puts them inline with each style/rule

### CODE REVIEW

**Comment by TristanMNorton** [comment]
Love it.

**Comment by marcelmoreau** [comment]
+1

we are repeating our mq mixin blocks. we should make these into a loop in a future PR

**Comment by marcelmoreau** [comment]
Instead of separate variables and mixins, I went ahead and added a single mixin to handle this by looking in a sass map. 

I also removed the responsive tester. If people want that, they can include their own.

**Comment by marcelmoreau** [comment]
This could use another look in terms of +1 and/or discussion

**Comment by mbfitz** [comment]
@marcelmoreau - is there a reason why you changed all of the MQ declarations to medium instead of some medium, some large like they were before?

**Comment by marcelmoreau** [comment]
no, that is an oversight

**Comment by marcelmoreau** [comment]
updated

**Comment by marcelmoreau** [comment]
Can people please review?

**Comment by TristanMNorton** [comment]
Looks good to me. Much cleaner.

**Pull request merged**
