### PR TITLE
Laravel mix and fontawesome v5

### PR DESCRIPTION
**Pull request by marcelmoreau**
There is a lot going on here.

- Added in Laravel Mix
- removed all gulp tasks from gulpfile.js except a Sassdoc task for our Sassdoc component documentation
- added in CDN for Font Awesome v5 professional
- swapped out instances of FA v4 HTML for v5
- added a sticky-element component entry to be listed on our components page even though it has no sass mixin

@jeffturcotte I am pinging you like you said re: this PR

### CODE REVIEW

**Comment by marcelmoreau** [comment]
- this needs an updated readme
- confirm that the stylesheet's sourcemap works correctly

**Comment by marcelmoreau** [comment]
- updated readme
- updated fontawesome mixin

I cannot get Sass sourcemaps to work correctly and I need help. I added a line [from this Issue](https://github.com/JeffreyWay/laravel-mix/issues/879#issuecomment-338426424) to the webpack.mix.js and it helped but it's still not working correctly. When visiting the /demo/accordion.html page, I expect to be able to utilize browser web tools where inspecting accordion styles maps the generated css to its respective source within _components.scss. It does not do this. I am hoping someone can look at this, otherwise I will hassle someone when I am in the office.

**Comment by marcelmoreau** [comment]
Sourcemaps working correctly. looking for feedback from peers, please.

**Comment by marcelmoreau** [comment]
Will likely merge this in Friday (04/06/2018) @mbfitz @JTQC @aaronmclayton @khamer

**Comment by mbfitz** [comment]
+1  this looks good to me!!

**Pull request merged**
