### PR TITLE
Handbook-inspired Refinements

### PR DESCRIPTION
**Pull request by khamer**
This pull request includes all the updates I've made as a result of using the current boilerplate on Handbook.

I've also forked Handbook and applied these styles - http://khamer.github.io/handbook/
#### SASS

I did this work after rewriting Boilerplate into SASS, as it felt like it would make some of this easier. I also found styling navigation in particular, to be much clearer with SASS than the CSS itself was. We don't have to continue with the SASS version, but if we like the SASS version more perhaps that is something we want to consider. I did follow very specific conventions when writing SASS, but that's a separate topic.

I've done some post-SASS formatting just to make the CSS more pleasant, but I'm sure more could happen.
#### Header Color

I switched these to dark grays, which was the direction Jeff was headed. I used two dark gray colors inspired by the colors used [here](http://windows.microsoft.com/en-us/windows-8/meet).
#### Navigation

I've changed the navigation to only change text colors with active state and removed the 'tab-like' background so that even in places where there is no secondary navigation (such as Handbook), the navigation doesn't look awkward.
#### Menus

I change the DOM structure for the dropdown menus slightly. I've introduced a `.dropdown` class, which allows for the dropdown menu to contain more than a single `ul`. This seems to match better with the sites we build. Also, it allows for crazier things, like full width (wider than `.container`) dropdowns, etc.

I **did not change** the DOM per Jeff's suggestion, as I wanted to keep the implementation for the secondary navigation and primary navigation separate, for sites that either want to implement only one or the other.
#### Fonts

I tried out some fonts and talked to Creative. I'm going to switch back to Open Sans, which is what I was using before we switched to Georgia. Open Sans is popular, clean, and very generic.

I also changed our body font-family back to `Arial, Helvetica, sans-serif`, as this is the font stack we should be using for body content, as its considered a best practice, web safe font stack.

Lastly, Creative pointed out that Handbook, being an iMarc site and iMarc branded, should be using iMarc fonts, so we should use Fjord instead of Open Sans there.
#### Polish

I did some basic polish here and there. I tweaked some colors, added a box-shadow to the dropdowns, and fixed a bug with button margins (that we accidentally introduced in the first place.)

### CODE REVIEW

**Comment by khamer** [comment]
I did change the `aside.primary` to be fluid width (from static, absolute positioned) finally, as I relent, that's more popular. This doesn't match up with the overrides for Handbook though.

**Comment by davetufts** [comment]
1) Is the right nav working here - http://khamer.github.io/handbook/frontend

2) Also, note the code blocks - http://handbook.imarc.net/frontend#HTMLFormatting vs http://khamer.github.io/handbook/frontend#HTMLFormatting - in the old one you could scroll to see all the code. 

3) Fonts - I'm fine with the web-font headline, but I really miss the nice Helvetica light. It seemed much more presentable.

4) Handbook Fonts - I agree with creative. That's what I said in the Workshop ticket. We're trying to finalize BP and we're temporarily using Handbook as a test site with actual content. "Once we're happy, Handbook can start evolving on its own and be more iMarc branded (but that's another ticket for another day)"

5) Torso - Mac/Chrome - the torso doesn't seem contained.

**Comment by khamer** [comment]
1. Yes.
2. That was because of a typo on a div tag, (same as 5.) I've fixed this.
3. As for Helvetica Neue Light, what we were doing before was bad. We had 'Helvetica Neue Light' with a font-weight of bold or 600 in places, which is scenario Paul wanted to make sure we always avoid, as it causes the faux bolding to happen. I don't know whether 'Helvetica Neue' with a font-weight of 300 will render as Helvetica Neue Light, but Arial doesn't support a font-weight of 300 anyway. If Arial/Helvetica is too heavy, we should look at other web safe font stacks or consider using a webfont on the body text, but I'd be more inclined to just use our typical `Arial, Helvetica, sans-serif`.

**Comment by jeffturcotte** [comment]
@khamer Is this ticket still relevant? if not, close it.

**Comment by khamer** [comment]
Yes, this is resolved.

**Pull request closed without merging**
