### PR TITLE
Component accordion

### PR DESCRIPTION
**Pull request by TommyChanthaboune**
# Simple accordion component
## Emmet

`.accordion>.accordion-group>(button{header}+div>{lorem ipsum})`
## Plugin Options

| Option | Type | Default | Description |
| :-- | :-- | :-- | :-- |
| hiddenOnLoad | Boolean | true | Hide contents on Load |
| singleOpen | Boolean | true | Only open one at a time. |
## JS Example

``` javascript
$(function () {
    var $accordion = $('.accordion');
    $accordion.accordion({
        hiddenOnLoad: true,
        singleOpen: true
    });
;});
```

### CODE REVIEW

**Comment by marcelmoreau** [comment]
Thanks!
- I like how you used `button` and not `a` for the controls
- Can we remove anything that is non-accordion from this PR? I see modifications to our reset here.
- The indentation got blown away in the _components.scss file. Can we change it back to how it was? 4 spaces for an indent
- I think it makes sense to rename the wrappers to be `.accordions > .accordion` as opposed to `.accordion > .accordion-group`. We would often do this (for better or for worse) over the years when naming many things within a thing. [Form element markup](http://handbook.imarc.com/frontend#FormElementMarkup) is a good example of that.
- Please rework the plus/minus icons. We have a dedicated mixin for fontawesome icons. You can see an example of a pseudo-element implementation from our [master page](http://imarc.github.io/boilerplate/#Pseudo-element) and [SCSS](https://github.com/imarc/boilerplate/blob/gh-pages/css/styles.scss#L644)
- We should probably use `th` elements for the first row of your Plugin Options table so they stand out more.
- Thanks for showing all accordion content if JS is off. Can we also hide the plus icon in this scenario? You may consider using a dedicated fontawesome element in this scenario.

**Comment by TommyChanthaboune** [comment]
- Great
- Changes to reset is just updating the code element to show code examples correctly. Before it was this ugly yellow on brown that didn't keep line breaks. Another change is just adding the mixin to a class.
- Fixed
- I don't agree this is semantic but I'll roll with it for now.
- Fixed
- Ok
- Sure

**Comment by marcelmoreau** [comment]
- if we want to think the naming through even more, you could consider `.accordion > .bellow` per the attached image
- please update emmet in HTML file and SCSS with whatever you go with. Right now SCSS shows old. Also, it does not output an `h3`
- comb `_components.scss` file for alphabetical
- first `:after` pseudo is missing double colon
- rename your plugin file name to match the existing naming convention of `thing.plugin.js`

accordion-diagram

**Comment by TommyChanthaboune** [comment]
- I don't think using `.bellow` is any better. The other way is fine for now.
- fixed
- fixed
- fixed
- fixed (js file names should be camelCase )

**Comment by marcelmoreau** [comment]
@khamer I think you may have missed this one while you were out. If you can check it out, that would be great. Would love to merge it in Tuesday, 11/1/16.

**Comment by marcelmoreau** [comment]
@khamer @jeffturcotte quick eyes here would be appreciated

**Comment by khamer** [comment]
- First, there's a mix of tabs and spaces - we should make sure it's all spaces.
- It'd be nice to beef up the mixin's comment to a full sentence instead of just a single word.
- There's some very tiny JS formatting things:
  - line 21 - I'd use `plugin.settings =` instead of `this.settings =` just to be slightly more clear
  - line 39 - needs whitespace before the first `(` and after the last `)`

I think I would have been more likely to markup an accordion like

``` html
<div class="accordion">
    <div>
        <h3>Clickable Header</h3>
        <div class="content">
            <p>...</p>
        </div>
    </div>
    <div>
        <h3>Another Clickable Header</h3>
        <div class="content">
            <p>...</p>
        </div>
    </div>
</div>
```

I feel like most accordions use the headers themselves as clickable elements instead of separate button elements, with some minor styling to indicate that the header is clickable and expands. Maybe even include a class on the headings in case they want to use something other than an h3. Also, I'd probably use `.accordion` for the outside and `.accordion > div` for the inside to avoid the `.accordions`/`.accordion` thing.

**Comment by marcelmoreau** [comment]
@TommyChanthaboune please implement Kevin's feedback provided you feel good about it

**Comment by marcelmoreau** [comment]
- do not replicate header within .content
- Emmet is not matching the markup....Note that there is an Emmet line in the HTML file and also the _components file

**Comment by marcelmoreau** [comment]
- wrapper this should probably be `.accordion` instead of `.accordions` per Kevin's comment
- the mixins in the _components.scss file should be alphabetical. please move this one to the top.
- can you make more line breaks in the components file

**Comment by marcelmoreau** [comment]
-  in the mixin you do not need the ampersand selector & > div...it can just be > div
- the &::after pseudo has an empty line at its block

**Pull request merged**
