### PR TITLE
Normalize as a reset

### PR DESCRIPTION
**Pull request by aaronmclayton**
Using normalize.css as a alternative to a reset, handling common Browser inconsistencies.

Normalize aims to:
- Preserve useful browser defaults rather than erasing them.
- Normalize styles for a wide range of HTML elements.
- Correct bugs and common browser inconsistencies.
- Improve usability with subtle improvements.
- Explain the code using comments and detailed documentation.

http://nicolasgallagher.com/about-normalize-css/

- Can be easily updated via `npm`

I feel strongly that this will fix many of the little bugs we see, not just across IE, but between Safari, Chrome, Firefox and Edge. Flexbox inconsistencies, padding and margin issues, should be eliminated. Personally I have used Normalize on all my projects since its inception and it's been a life saver.

### CODE REVIEW

**Comment by marcelmoreau** [comment]
Thanks for taking the initiative to do this. Do we have a few examples of where Boilerplate was coming up short in terms of visual bugs? Our form elements? Something else?

Here is why I am not +1'ing at this time:

- For this, I would just download normalize and import it into the main styles.scss like mixins/components instead of importing from node_modules
- There is commented out code here (the base section)
- We tend to like our previous font-stack (Arial, sans-serif)
- [Pseudo-elments should use two colons, not one](https://github.com/imarc/boilerplate/blob/NormalizeCSS/css/styles.scss#L206)
- This seems to REMOVE the `box-sizing: border-box` from ALL elements. We really rely on this.
- As far a I know, we should not be committing package-lock.json files

**Comment by chantron** [comment]
My two cents:

* CSS resets have been a best practice for ever and normalize.css has been the industry standard for resets for a while now. It should be included in every project for the reasons Aaron has pointed out.
* Normalize wouldn't affect the box-sizing except on legend, hr and checkbox/radio elements. 
* When possible you want to install third party stuff via NPM, it makes life so much easier.
* You _should_ be comitting package-lock.json, NPM will read that file and install the exact versions listed when installing.

**Comment by khamer** [comment]
I'm not opposed to normalize, but it's the other changes I'm not sure if make sense:

* I think you need to regenerate styles.css before you commit it - it doesn't look like it matches what styles.scss would compile to
* our reset rules do things normalize doesn't; such as set all elements to box-sizing border-box, reset padding/margins on all elements, etc.
* If we're adding specific fieldset rules, they should be in the form section, not immediately after the body tag
* I'm not sure why you're removing the padding on dd elements.

And commented on other points @marcelmoreau and @chantron mentioned –

* Yes, we should use NPM to install this and not download and copy it into boilerplate.
* Yes, we should not commit old, commented out code.
* I'm not sure why you're changing the font stack either.
* psuedo-elements should use two colons.
* Typically for a library like this (not a site) I'd say that we **should not** commit a package-lock.json, as then we wouldn't pick up normalize's fixes. But, because we also use boilerplate as a 'starter' and given that there's been a committed package-lock.json already for a while, I think it's fine to keep the package-lock.json. If we want to talk about removing it, we should do that separately.

**Comment by aaronmclayton** [comment]
Changes have been made that @marcelmoreau and @khamer mentioned

- Font stack is back to original
    - My thought here was since we were using TypeKit in most of our projects, that it would replace the stack anyway, so it was to go to something that was default for each system. Then I thought more and decided against it since it's a website more likely than an app we build.
- Using `normalize-sass` instead of `normalize.css` npm module.
    - The comments are still there though. If this is a area of contention, there is another route.
- Differentiate between pseudo elements and classes for `::before, ::after`
    - My bad
- Move `fieldset` reset to forms
- Commit `styles.css`, `styles.css.map`, `package.json` and `package-lock.json` builds
- Remove commented code
   - My bad

---------------

**Comments on original questions:**
- Removing padding on `dd` element
    - Normalize defaults to padding on the `dd` element. So there was double padding. 
- `box-sizing: border-box` change
    - It's a recommended practice to set only the `html` element to have the `box-sizing` value, then all other elements can inherit. This reset gives you more flexibility. You can use `content-box` or `padding-box` (where supported) at will, without worrying about a universal selector overriding your CSS. (https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/)

**Comment by chantron** [comment]
> The comments are still there though. If this is a area of contention, there is another route.

I don't think the comments are removed with the current output style.

**Comment by aaronmclayton** [comment]
@chantron That was going to be my way of removing them was through gulp-sass options. However, I agree with @khamer that it needs to be converted to mix so we can be in line with our current process. In any case, options with gulp or mix can eliminate these.

**Comment by khamer** [comment]
Looking pretty good. I'm not worried about comments in the output - just having old, commented out code, which is resolved now.

Last minor things -
* there's a change to the icon positioning for .messaging - doesn't seem related to this PR, but just wanted to make sure it was intentional and there was a reason for it.
* the CSS rules in fieldset {} just need minor cleanup: space after the colons and alphabetized.

It's not strictly necessary to do for this PR, but it'd be good to try to find/make an example where this behaves differently than what we had before. When we put Boilerplate together, we used chunks of normalize.css, but not all of it; it'd be handy when we explain why we do this to be able to point at a difference or two.

**Comment by marcelmoreau** [comment]
just bumping this so it's fresh in @aaronmclayton's mind

**Comment by aaronmclayton** [comment]
@khamer Making a good example and following set practices are always necessary for a PR in my opinion. Good call there.

To address the two minor things:
- The `.messaging` positioning was just a fix I noticed. I can revert it for this PR and open another for sure.
- CSS rules in `fieldset` have been addressed to follow guidelines.

**Pull request merged**
