### PR TITLE
adding login component

### PR DESCRIPTION
**Pull request by mbfitz**
Here's a basic login component. Note: it obviously doesn't function, but it's just the basic UI with inputs, buttons, forgot/remember links and checkboxes. I also added some focus styles to the inputs. Let me know if you think I missed anything!

### CODE REVIEW

**Comment by marcelmoreau** [comment]
- Can we set a max-width on this entire thing?
- the wrapper for the password input should be `.password` and not `.text`
- can we put all the "controls" on one line w/ flexbox? example: http://dev.business.weather.com/partners/portal/login
- Let's have 'Forgot Password' say 'Forgot your password?'
- minor: should we use a background-color on the .login div instead of a border?

**Comment by mbfitz** [comment]
- I was going to put a max-width, but then I was afraid of adding too much style to it, and thought we should leave that up to a per-site basis? I've seen logins that are like 500px wide, and ones that are full-width. 
- I'll fix the .password class
- Yes! - will move the forgot password and remember me next to the login button
- Will update the forgot password text
- I thought adding a background color would be too much, but maybe that would be better than using a border? Either way was trying to keep styling to a minimum...

**Comment by marcelmoreau** [comment]
- I would argue that all of these should have a max-width and authors can remove if need be. Most of the time, I feel they will just be modifying the max-width.
- Perhaps the background color can be the same #EEE as [features](http://imarc.github.io/boilerplate/components/features.html). Maybe one day, we can do a mass find-and-replace once creative adds minor touches to this stuff

**Comment by mbfitz** [comment]
updated based on marcel's feedback! link to view: https://htmlpreview.github.io/?https://github.com/imarc/boilerplate/blob/27196546224e5acb3c100499e600d9229c51f1ad/components/login.html

**Comment by mbfitz** [comment]
and fixed some responsive stuff

**Pull request merged**
