### PR TITLE
Components modal

### PR DESCRIPTION
**Pull request by mbfitz**
Here's the initial PR for the modal component. I documented a few different examples, and linked out to Magnific's documentation for more information. Let me know if I can make anything more clear or should update any html/scss. Thanks! 

Preview here: https://htmlpreview.github.io/?https://github.com/imarc/boilerplate/blob/5805d532f237408bbaed6585a56e4dbabdbc34bf/components/modal.html

### CODE REVIEW

**Comment by marcelmoreau** [comment]
- update mixin name to modal and ABC styles
- update class names to either: whatever magnific uses, or something we like
- change last example to use a span instead of anchor
- merge in gh-pahes...link the version of jquery to 3x/whatever the other components use
- can we make each example use the same class for the container? for example, if we need to modify a close button, how would we style it?  we should document what
- can we remove the removalDelay option? let's have the least amount of options we can like the carousel example.
- javascript spacing is off
- line 135 ZOOM IT
- wipe out the mid-click thing

**Comment by marcelmoreau** [comment]
- we just need to use the jquery version all the other components use
- can we re-name our popup example things to be more uniform and with 'modal' in the name? Maybe:
  - modal-image
  - modal-iframe
  - modal-video
- If we do the previous, don't forget the emmet examples

**Comment by marcelmoreau** [comment]
plz also make background be background-color  💯

**Comment by mbfitz** [comment]
@marcelmoreau - all set!

**Comment by marcelmoreau** [comment]
- Please remove the line that references this as a "carousel library"
- please merge gh-pages in and update the emmet/example markup to be sassdoc friendly
- give everything another look to make sure things are good
- regenerate docs and update PR

**Pull request closed without merging**
