### PR TITLE
Component user profile

### PR DESCRIPTION
**Pull request by TommyChanthaboune**
# Simple User Profile Component
## Emmet

`.user-profile>(.portrait>img+h3.name+p.title+(a*2)+ul.social)+.biography`
## Description

Two columned components. One has a portrait with name, title and contact info. The other can contain any other kind of content or actions.

### CODE REVIEW

**Comment by marcelmoreau** [comment]
I am thinking this is looking and acting like the Leadership/Management component we have yet to build (image on one side w/ optional contact info/social and bio on the other side). Curious to hear what people think tomorrow at build-a-thon. It's been so long since i have worked on a CPA site, I am not even sure what we are thinking for this. Perhaps these two patterns should be the same thing.

**Comment by marcelmoreau** [comment]
@mbfitz I would rename this branch to be the leadership/management component we talked about (if you have not already started it)

**Comment by mbfitz** [comment]
@marcelmoreau - I can do that

**Comment by mbfitz** [comment]
this turned into dossier

**Pull request closed without merging**
