### PR TITLE
Removing table of contents

### PR DESCRIPTION
**Pull request by khamer**
Out of all the websites I surveyed using boilerplate, only one had kept the table of contents in sync with the actual SASS. I think it's better to have no table of contents than an incorrect one.

### CODE REVIEW

**Comment by Tchanthaboune** [comment]
+1

**Comment by marcelmoreau** [comment]
I feel this is unfortunate as it can help immensely with organization. That said, if we can't maintain a TOC, I doubt we can maintain separate stylesheets.

**Comment by davetufts** [comment]
If my vote counts (which it probably shouldn't because I never use this), I'd vote +1

**Comment by marcelmoreau** [comment]
Also, when having to style elements across multiple breakpoints, the TOC acts as a good structure to know what ORDER styles should remain in. Also, it also can act components-esque... knowing where to look.

**Comment by mbfitz** [comment]
I try to keep my TOC's as accurate as possible, but admit it slips through sometimes. I'm fine either way.

**Comment by Tchanthaboune** [comment]
@marcelmoreau I don't agree with your first statement. In fact, a list of imports can be self documenting. For example

``` scss
//in docroot/css/styles.css

@import 'reset'
@import 'variables'
@import 'mixins'

```

Technically we can write javascript in one file too but we don't because it's helpful to keep code modularized.

HOW we separate out SCSS files is still up in the air. Whether it be by page, component, or whatever I still think people will find any code that is broken up into logical pieces is more digestible, maintainable and easier to reuse from project to project.

**Comment by jeffturcotte** [comment]
-1. If somebody doesn't want to follow that structure or wants to get rid of it when they start a project, just delete the comment. Easy. I admit this change has very little effect on anything, so it doesn't really matter.

Whether or not it reflects the site after months of work has been done, it reflects the initial state of boilerplate and is a nice reference.

**Comment by khamer** [comment]
Maybe we just need to make sure we're updating the TOC more, or revisit the sections. For example, it seems pretty common for Layout SCSS to be pushed 'further down' (below Typography in particular.) Thoughts?

**Pull request closed without merging**
