### PR TITLE
Component mobile nav

### PR DESCRIPTION
**Pull request by TommyChanthaboune**
# Mobile Navigaiton
## Plugin Options

| Option | Type | Default | Description |
| :-- | :-- | :-- | :-- |
| toggleClass | String | 'menu-toggle' | This class toggles the main menu. |
| menuToggleClass | String | 'open' | Name of the class that toggle menus. |
| wrapper | String | 'wrapper' | Class name of the wrapper of the entire site |
| subMenuClass | String | 'dropdown' | Class name of the sub menus |
| directionFrom | 'string' | 'left' | 'Can open from left or right |
## JS Example

``` javascript
$(function () {
    var $mobile = $('.mobile');
    var $filters = $('.filters');

        $mobile.mobileNavigation();
        $filters.mobileNavigation({
            directionFrom: "right"
        });
});
```
## Changes to boilerplate
1. Add wrapper to entire site
2. Change desktop navigation from float to flexbox
3. Change filenames from dashes to camel case
## Additions to boilerplate
1. Mobile Navigation Markup
2. Add additional .header-content wrapper in header
## Notes:

Mobile markup is separate from Desktop however utilizes the same pattern.

### CODE REVIEW

**Comment by marcelmoreau** [comment]
- please test in iPhone and iPad via browser stack
- remove fourth level

**Comment by khamer** [comment]
- I would make configuration use selectors instead of classnames - that's more normal for jQuery plugins, and every instance you use them besides one you convert them to selectors. This would also help you get rid of the toSelector method.
- `menuToggleClass` may need to remain a classname - but I'd be okay with hardcoding that to 'open' as well. I don't see a lot of value in making that configurable.
- You need to document. For a plugin this size, I'd recommend adding documentation to both the mixin and to `mobileNavigation.jquery.js`. You should at least document what all the options are and what they do, but getting the Emmet structure in there too would be great.
- I think `mobileNavigation.jquery.js` should be named `mobileNavigation.plugin.js` to be consistent with the others.
- I wouldn't include a separate version in `mobileNavigation.plugin.js` that is separate from the version that Boilerplate has. The other metadata in there (author) is fine.
- Lastly, personally I think these kinds of overlays, you should be able to close them by tapping/clicking off of the overlay. It's fairly ubiquitous convention that I immediately noticed we were breaking.

**Comment by marcelmoreau** [comment]
@TommyChanthaboune please implement any changes needed

**Comment by TommyChanthaboune** [comment]
- ~~I would make configuration use selectors instead of classnames - that's more normal for jQuery plugins, and every instance you use them besides one you convert them to selectors. This would also help you get rid of the toSelector method.~~

- ~~`menuToggleClass` may need to remain a classname - but I'd be okay with hardcoding that to 'open' as well. I don't see a lot of value in making that configurable.~~

- ~~You need to document. For a plugin this size, I'd recommend adding documentation to both the mixin and to `mobileNavigation.jquery.js`. You should at least document what all the options are and what they do, but getting the Emmet structure in there too would be great.~~

- ~~I think `mobileNavigation.jquery.js` should be named `mobileNavigation.plugin.js` to be consistent with the others.~~

- ~~I wouldn't include a separate version in `mobileNavigation.plugin.js` that is separate from the version that Boilerplate has. The other metadata in there (author) is fine.~~

- ~~Lastly, personally I think these kinds of overlays, you should be able to close them by tapping/clicking off of the overlay. It's fairly ubiquitous convention that I immediately noticed we were breaking.~~

All but the first thing was finished as discussed. Please review this when you have the chance.

**Comment by marcelmoreau** [comment]
I am merging this into gh-pages mostly so we have a remote page to test with. Not looking to test with Browserstack local development.

**Pull request merged**
