### PR TITLE
Component testimonial

### PR DESCRIPTION
**Pull request by mbfitz**
Hey guys! Please review the testimonial components I put together. One is super simple center-aligned quote + attribution, and the other adds an option to include an asset (logo, avatar, whatever). Let me know if I missed anything. Thanks! 

https://htmlpreview.github.io/?https://github.com/imarc/boilerplate/blob/07725679de0cc9b545c3a826c74e8713e27b7441/components/testimonial.html

### CODE REVIEW

**Comment by marcelmoreau** [comment]
- you can totally do this with one variation – no need for an .assets version
  - just add a flex container around the blockquote and image and we can set some flex-basis on image's wrapper. I don't even see any styles related to your .assets selector.
- never style to .container...this should never be touched IMO. it's always the same thing ion every project and should never behave differently
- use two semi-colons :: for pseudo-elements
- christian would like to use normal quote characters from the font itself
- use flexbox instead of floating the image
- we typically do not use clearfix on .container anymore

**Comment by marcelmoreau** [comment]
This looks good

Apologies if this is still in process, but I am going over these this morning so there may be repeats...when ur hot ur hot

- in most of our sites, we try to reply on margin-bottom all-the-time-if-possible so we can remove the margin-top from this component IMO
- you don't need `width: 100%;`
- use a general sibling selector instead of adjacent [here](https://github.com/imarc/boilerplate/blob/da5576ad65c3f7b098ef3172e8ca165e02979b9b/css/_components.scss#L640) so it's more robust
- image 
  - blow this up to like 900x900. this could happen if we do not resize images on a site. check it in mobile view. it is large.
  - tablet view, the image is very small
- let's use a fake name and not Jonathan's...wouldn't want him googling and being like "wot"
- I'd say you could use one `font-size` from mobile through desktop...one less rule
- let's not use `$brand-orange` for a color. If one of the first things an Imarcian does is place their brand colors in the stylesheet, they will get an error. Don't think any other components use a variable based color in this fashion (I think $border and $meta usage could be fine)
(https://github.com/imarc/boilerplate/blob/da5576ad65c3f7b098ef3172e8ca165e02979b9b/css/_components.scss#L640)
- pseudos still need double colons
- can we use the explicit `background-color` instead of `background`?
- fix the emmet in _components.scss...I added a revised emmet in the HTML just now...they should match

**Comment by mbfitz** [comment]
This is ready to look at again. I incorporated all of Marcel's feedback EXCEPT the font-size, i think it benefits being smaller on mobile because otherwise it's huuuggeee and takes up too much space. :) (but can easily remove if others agree with him)

**Comment by marcelmoreau** [comment]
- The image is still very tiny as in the tablet view

**Comment by marcelmoreau** [comment]
there also appears to be a css directory within our normal css directory

**Comment by mbfitz** [comment]
these are fixed! flexbox chrome bug caused the image to be tiny and i think gulp created the extra css file

**Comment by marcelmoreau** [comment]
- reordered the SCSS rules to match the HTML order
- we only need one media query declaration. No need to go in and out of MQs in such a small block of code
- removed flexbox on blockquote’s pseudo elements
- gave the logo image a max-width on the stacked version. it was huge
- the quote was so thin on medium breakpoint that I chose to flex this at the large breakpoint

**Pull request merged**
