### PR TITLE
Component scroll to section

### PR DESCRIPTION
**Pull request by marcelmoreau**
Uses: https://github.com/cferdinandi/smooth-scroll

We can document the relevant options and settings in the Jan 13- Jan 27 phase of Boilerplate

### CODE REVIEW

**Comment by marcelmoreau** [comment]
@mbfitz @TommyChanthaboune @khamer any comments here?

**Comment by TommyChanthaboune** [comment]
Why is this library chosen over an in house jQuery plugin or third party jQuery plugin  ?

**Comment by marcelmoreau** [comment]
This is not a third party plugin?

**Comment by TommyChanthaboune** [comment]
third party **jQuery** plugin

**Comment by marcelmoreau** [comment]
It was chosen because I didn't think we were beholden to jQuery and that vanilla JS is ok

**Comment by TommyChanthaboune** [comment]
We're not but it is very very rare that jQuery isn't included in our projects anyway. At the very least I think this vanilla javascript plugin should have some sort of jQuery wrapper so there is a consistent interface with our components that require JS.

I really don't see the value of introducing a third party codebase for this particular component anyway. I feel like the majority of this third party plugin is replicating what is already available in jQuery and the logic to replicate the scroll to behavior as a jQuery plugin is relatively small.

**Comment by khamer** [comment]
Using [cferdinandi/smooth-scroll](https://github.com/cferdinandi/smooth-scroll) doesn't bother me, here's my thoughts:

* When we use a third party lib like that, we shouldn't rename it like we did. It's not obvious whether I can upgrade this script to a newer version, whether you've customized it, etc.
* The feature set of [cferdinandi/smooth-scroll](https://github.com/cferdinandi/smooth-scroll) looks pretty good to me; It's decently popular; I expect we run into fixed headers fairly often, and being able to control the offset and easing is nice too. It is more complicated than what I expected for this PR, but I don't think that's problematic - just more for you to document before we merge it in.
* I probably would have used the `smoothScroll.animateScroll()` functionality instead of of the data attributes; the data-attributes feel messier to me, and less consistent with how all the other plugins work.

All said, the only thing that I think blocks merging this in is documentation and make it more clear that you're using a third party lib, smooth-scroll.js, to provide the functionality.

Oh, if it helps, here's a link to this PR as a demo - https://htmlpreview.github.io/?https://raw.githubusercontent.com/imarc/boilerplate/component-scroll-to-section/components/scroll-to-section.html

**Comment by marcelmoreau** [comment]
I cannot get this to work properly using `smoothScroll.animateScroll()`. I will wait until Friday at our workgroup to discuss.

**Comment by marcelmoreau** [comment]
- added more documentation with link to script
- renamed script file 

- needs `smoothScroll.animateScroll()` implementation
- needs proper wrapper for continuity with our other scripts

**Pull request merged**
