### PR TITLE
Keyes suggestions

### PR DESCRIPTION
**Pull request by keyesatimarc**
Few minor tweaks to get Boilerplate more in line with where I sometimes start. I've added comments to each of my commits which detail the changes, but the biggest thing is the addition of a CSS-only based responsive indicator and switching up the way we handle breakpoints. Still bottom up, but more of them, and color coded for ease of tracking.

### CODE REVIEW

**Comment by marcelmoreau** [comment]
- separate mixin file is awesome, thanks
- I am a big NO on increase the default body copy. I feel our designs are too BIG
- container padding stuff is cool
- paragraph margin upped. I am often told to bring these down. This relates back to BIG
- I don't see the margin reset for headers but we will talk about it
- I feel people need to memorize colors for whatever screensize they're looking for. Why not just call them small, medium, large, xl, etc?

**Comment by marcelmoreau** [comment]
+1
- separate mixin file
- container mixin
- pixel gutter value
- prism rainbow media queries
- number weights, body width, arial

-1 
- `$rem` variable has gotta go. native `rem` unit works well
- against increased paragraph spacing. Almsot every project, I am instructed to tighten things up per the client

To do:
- I'd add very short description of the color rainbow under the Media Queries heading (about small-to-large) incase anyone is a dumbass like me 
- please make sure all pseudo-elements to standardized `::` instead of `:`
- update table of contents in styles.scss
  - remove mixins
  - remove `@imports` and place them right after table of content like all sass files do
- margin reset is there as part of [our reset](https://github.com/imarc/boilerplate/blob/gh-pages/css/styles.scss#L324)

**Comment by mbfitz** [comment]
**+ 1 to all this:** 

- separate mixin file
- container mixin
- pixel gutter value
- number weights, body width, arial

**-1 agree with Marcel on these points**

- $rem variable has gotta go. native rem unit works well
- against increased paragraph spacing. Almsot every project, I am instructed to tighten things up per the client

**Also still not sold on this, so not a +1 or -1, just a suggestion:** 
- prism rainbow media queries
- could we possibly just put this in a separate branch so we can all try it out first before adding it to the official BP? or maybe only include it as a mixin in the styles (like other components) so we can leave it out if we choose instead of having those styles in the css by default.

**Comment by marcelmoreau** [comment]
- I [made a branch](https://github.com/imarc/boilerplate/tree/keyes-suggestions-marcel) where I re-named the prism breakpoints to be sized-based but kept a color dot. Instead of 6 media queries, there are 3. [See this video](https://vimeo.com/239469498)
- removed the $rem var
- left paragraph spacing alone
- removed block display on images. this conflicts with some components and is a bad idea anyway IMO

**Pull request merged**
