### PR TITLE
Revisiting mixins based on actual use

### PR DESCRIPTION
**Pull request by khamer**
I did a quick survey of seven recent sites, and measured which mixins were used and which weren't. this PR is for a slightly improved version of the fontawesome mixin, as well as dropping the following:
- no-bullets
- link-states
- bg-gradient

Thoughts before I merge it in?

### CODE REVIEW

**Comment by Tchanthaboune** [comment]
+1

**Comment by marcelmoreau** [comment]
I am fine with killing gradient mixin for sure.
I love no-bullets.
I enjoy the link-states mixin as I use it, however, perhaps others do not like it or have not used it.

See an example of link-states here: http://codepen.io/marcelmoreau/pen/QjdKQW

**Comment by mbfitz** [comment]
I agree with Marcel - I think we should just kill the gradient mixin, but the no-bullets and link-states seem to be used more often

**Comment by khamer** [comment]
Here's my usage stats from the ~6 sites I surveyed. First number is the websites that used the mixin, the second number is the number of times the mixin was used total. So, for example, 'dropshadow' was used 12 times on only one site, whereas 'transition' was used 106 times across five different sites. (Oh, and bolded ones are the ones that are part of Boilerplate.)
- **columns**: 6 (10)
- **container**: 6 (17)
- **grouping**: 6 (74)
- **transition**: 5 (106)
- **fontawesome**: 4 (17)
- **header-font**: 3 (10)
- **messaging**: 3 (9)
- naked_lists: 3 (16)
- **link-states**: 2 (15)
- backgroundHalves: 1 (4)
- **bg-gradient**: 1 (1)
- circular-frame: 1 (9)
- dropshadow: 1 (12)
- listing: 1 (2)
- **no-bullets**: 1 (3)
- pattern-left: 1 (4)
- pattern-right: 1 (4)
- post: 1 (7)

Are no-bullets and 'naked_lists' different ways of doing the same thing? no-bullets only showed up used 3 times on one site, but if it's the same thing as naked_lists with just a different name, maybe we just need to unify those.

**Pull request closed without merging**
